// Ride gallery overlay: loads gallery.json (generated by
// scripts/generate_gallery_json.py) and renders route cards into the
// fullscreen gallery dialog. Each card owns a small interactive 3D map
// preview, framed from route metadata when available.

import {
  computeRouteOverviewCamera,
} from "./camera.mjs";
import {
  densifyRoute,
  enrichRoute,
  parseGpx,
  routeTotalDistance,
} from "./route.mjs";
import {
  DEFAULT_MAP_FOV_DEGREES,
  OVERVIEW_HEADING_OFFSET_DEGREES,
  OVERVIEW_MARGIN_FACTOR,
  OVERVIEW_MAX_RANGE_METERS,
  OVERVIEW_MIN_RANGE_METERS,
  OVERVIEW_RANGE_FACTOR,
  OVERVIEW_TILT_DEGREES,
  ROUTE_LINE_ALTITUDE_METERS,
  ROUTE_LINE_MAX_POINTS,
  ROUTE_LINE_SPACING_METERS,
} from "./tuning.mjs";
import { formatAltitude, formatDistance } from "./units.mjs";

export const GALLERY_ATTRIBUTION = "interactive previews from Google Maps Photorealistic 3D · map data © Google";

const DIFFICULTY_COLORS = {
  "Very Easy": "#4ec06f",
  "Easy": "#4ec06f",
  "Moderate": "#e8b74e",
  "Hard": "#e8823c",
  "Very Hard": "#d9542f",
  "Epic": "#d9542f",
};

const cards = [];
let els = null;
let previewStartRequested = false;

export async function initGallery(onLoadRoute, {
  shouldAutoLoadFirst = () => false,
  getCurrentRouteName = () => null,
  getDistanceUnits = () => "metric",
  getMaps3d = () => null,
  getMapLabelsEnabled = () => false,
} = {}) {
  let routes;
  try {
    const response = await fetch("./gallery.json");
    if (!response.ok) return;
    routes = (await response.json()).routes;
  } catch {
    return;
  }
  if (!routes?.length) return;

  els = {
    dialog: document.getElementById("galleryDialog"),
    grid: document.getElementById("galleryGrid"),
    count: document.getElementById("galleryCount"),
    attribution: document.getElementById("galleryAttribution"),
    closeBtn: document.getElementById("galleryCloseBtn"),
    browseBtn: document.getElementById("browseGalleryBtn"),
    browseCount: document.getElementById("browseGalleryCount"),
  };

  const loadRoute = async (route) => {
    await onLoadRoute(route.gpx, route.title);
    refreshCards(getCurrentRouteName, getDistanceUnits);
    els.dialog.close();
  };

  for (const route of routes) {
    els.grid.append(buildCard(route, loadRoute));
  }
  refreshCards(getCurrentRouteName, getDistanceUnits);

  els.count.textContent = `${routes.length} route${routes.length === 1 ? "" : "s"}`;
  els.attribution.textContent = GALLERY_ATTRIBUTION;
  els.browseCount.textContent = String(routes.length);
  els.browseBtn.hidden = false;
  els.browseBtn.addEventListener("click", () => {
    refreshCards(getCurrentRouteName, getDistanceUnits);
    els.dialog.showModal();
    void startGalleryPreviews({ getMaps3d, getMapLabelsEnabled });
  });
  els.closeBtn.addEventListener("click", () => els.dialog.close());

  if (routes[0].gpx && shouldAutoLoadFirst()) {
    await onLoadRoute(routes[0].gpx, routes[0].title);
    refreshCards(getCurrentRouteName, getDistanceUnits);
  }
}

function refreshCards(getCurrentRouteName, getDistanceUnits) {
  const currentName = getCurrentRouteName();
  const units = getDistanceUnits();
  for (const card of cards) {
    const loaded = card.route.title === currentName;
    card.root.classList.toggle("loaded", loaded);
    card.loadedBadge.hidden = !loaded;
    card.button.textContent = loaded ? "Loaded" : "Load route";
    if (card.distanceStat) {
      card.distanceStat.textContent = formatDistance(card.route.distanceMeters, units, 1);
      card.ascentStat.textContent = formatAltitude(card.route.ascentMeters, units);
      card.descentStat.textContent = formatAltitude(card.route.descentMeters, units);
    }
  }
}

function buildCard(route, loadRoute) {
  const card = document.createElement("article");
  card.className = "gallery-card";

  const thumb = document.createElement("div");
  thumb.className = "gallery-card-thumb";

  const previewMount = document.createElement("div");
  previewMount.className = "gallery-card-map";
  const previewStatus = document.createElement("span");
  previewStatus.className = "gallery-card-preview-status";
  previewStatus.textContent = "3D preview loading";
  thumb.append(previewMount, previewStatus);

  const loadedBadge = document.createElement("div");
  loadedBadge.className = "gallery-card-loaded-badge";
  loadedBadge.textContent = "LOADED";
  loadedBadge.hidden = true;
  thumb.append(loadedBadge);
  card.append(thumb);

  if (route.bars?.length) {
    card.append(buildMiniProfile(route.bars));
  }

  const body = document.createElement("div");
  body.className = "gallery-card-body";

  const title = document.createElement("h3");
  title.className = "gallery-card-title";
  title.textContent = route.title;

  const desc = document.createElement("div");
  desc.className = "gallery-card-desc";
  renderMarkdownDescription(route.description || "", desc);
  body.append(title, desc);

  let distanceStat = null;
  let ascentStat = null;
  let descentStat = null;
  if (route.classification) {
    const c = route.classification;
    const classLine = document.createElement("div");
    classLine.className = "gallery-card-class";
    const dot = document.createElement("i");
    dot.style.background = DIFFICULTY_COLORS[c.difficulty] ?? "#e8b74e";
    const label = document.createElement("span");
    label.textContent = `${c.difficulty} ${c.distanceClass} · ${c.terrainClass}`;
    classLine.append(dot, label);

    const stats = document.createElement("div");
    stats.className = "gallery-card-stats";
    const distance = buildStat("Length", "");
    const ascent = buildStat("Ascent", "accent");
    const descent = buildStat("Descent", "");
    stats.append(distance.wrap, ascent.wrap, descent.wrap);
    distanceStat = distance.stat;
    ascentStat = ascent.stat;
    descentStat = descent.stat;

    body.append(classLine, stats);
  }

  const button = document.createElement("button");
  button.type = "button";
  button.className = "gallery-card-btn";
  button.textContent = "Load route";
  button.addEventListener("click", () => loadRoute(route));
  body.append(button);
  card.append(body);

  cards.push({
    route,
    root: card,
    previewMount,
    previewStatus,
    previewRendered: false,
    loadedBadge,
    button,
    distanceStat,
    ascentStat,
    descentStat,
  });
  return card;
}

async function startGalleryPreviews({ getMaps3d, getMapLabelsEnabled }) {
  if (previewStartRequested) return;
  previewStartRequested = true;

  const maps3d = await resolveMaps3d(getMaps3d);
  if (!maps3d?.Map3DElement) {
    for (const card of cards) card.previewStatus.textContent = "3D preview unavailable";
    return;
  }

  for (const card of cards) {
    void renderCardPreview(card, maps3d, getMapLabelsEnabled);
  }
}

async function resolveMaps3d(getMaps3d) {
  const provided = getMaps3d?.();
  if (provided?.Map3DElement) return provided;
  try {
    return await window.google?.maps?.importLibrary?.("maps3d");
  } catch {
    return null;
  }
}

async function renderCardPreview(card, maps3d, getMapLabelsEnabled) {
  if (card.previewRendered) return;
  card.previewRendered = true;

  let route;
  try {
    const response = await fetch(card.route.gpx);
    if (!response.ok) throw new Error(`Could not load ${card.route.gpx}`);
    route = enrichRoute(parseGpx(await response.text()).points);
  } catch {
    card.previewStatus.textContent = "Route preview unavailable";
    return;
  }
  if (route.length < 2) {
    card.previewStatus.textContent = "Route preview unavailable";
    return;
  }

  const camera = previewCameraForRoute(card.route.previewCamera, route, card.previewMount);
  if (!camera) {
    card.previewStatus.textContent = "Preview camera unavailable";
    return;
  }

  const { AltitudeMode, Map3DElement, MapMode, Polyline3DElement } = maps3d;
  const map = new Map3DElement({
    center: camera.center,
    heading: camera.heading,
    range: camera.range,
    tilt: camera.tilt,
    roll: camera.roll ?? 0,
    fov: camera.fov ?? DEFAULT_MAP_FOV_DEGREES,
    mode: getMapLabelsEnabled?.() ? MapMode?.HYBRID : MapMode?.SATELLITE,
    defaultUIDisabled: true,
  });
  card.previewMount.replaceChildren(map);
  card.previewStatus.hidden = true;

  if (Polyline3DElement) {
    const spacing = Math.max(ROUTE_LINE_SPACING_METERS, routeTotalDistance(route) / ROUTE_LINE_MAX_POINTS);
    const linePoints = densifyRoute(route, spacing);
    map.append(new Polyline3DElement({
      altitudeMode: AltitudeMode?.RELATIVE_TO_GROUND,
      path: linePoints.map((point) => ({
        lat: point.lat,
        lng: point.lng,
        altitude: ROUTE_LINE_ALTITUDE_METERS,
      })),
      strokeColor: "#0a84ff",
      strokeWidth: 14,
      outerColor: "rgba(255, 255, 255, 0.72)",
      outerWidth: 0.35,
    }));
  }
}

function previewCameraForRoute(metadataCamera, route, mount) {
  const camera = normalizePreviewCamera(metadataCamera);
  if (camera) return camera;

  return computeRouteOverviewCamera(route, {
    tiltDegrees: OVERVIEW_TILT_DEGREES,
    headingOffsetDegrees: OVERVIEW_HEADING_OFFSET_DEGREES,
    marginFactor: OVERVIEW_MARGIN_FACTOR,
    rangeFactor: OVERVIEW_RANGE_FACTOR,
    minRangeMeters: OVERVIEW_MIN_RANGE_METERS,
    maxRangeMeters: OVERVIEW_MAX_RANGE_METERS,
    viewportAspect: mount.clientWidth && mount.clientHeight
      ? mount.clientWidth / mount.clientHeight
      : 16 / 9,
    fovDegrees: DEFAULT_MAP_FOV_DEGREES,
  });
}

function normalizePreviewCamera(camera) {
  const center = camera?.center;
  const normalized = {
    center: {
      lat: Number(center?.lat),
      lng: Number(center?.lng),
      altitude: Number(center?.altitude) || 0,
    },
    heading: Number(camera?.heading),
    range: Number(camera?.range),
    tilt: Number(camera?.tilt),
    roll: Number(camera?.roll) || 0,
    fov: Number(camera?.fov) || DEFAULT_MAP_FOV_DEGREES,
  };
  return [
    normalized.center.lat,
    normalized.center.lng,
    normalized.heading,
    normalized.range,
    normalized.tilt,
  ].every(Number.isFinite) ? normalized : null;
}

function buildStat(label, valueClass) {
  const wrap = document.createElement("div");
  wrap.className = "gallery-card-stat";
  const name = document.createElement("span");
  name.textContent = label;
  const stat = document.createElement("strong");
  if (valueClass) stat.className = valueClass;
  stat.textContent = "--";
  wrap.append(name, stat);
  return { wrap, stat };
}

function buildMiniProfile(bars) {
  const strip = document.createElement("div");
  strip.className = "gallery-card-profile";
  for (const bar of bars) {
    const el = document.createElement("i");
    el.style.height = `${bar.h}%`;
    el.style.background = bar.c;
    strip.append(el);
  }
  return strip;
}

function renderMarkdownDescription(text, container) {
  const paragraphs = String(text).trim().split(/\n{2,}/).filter(Boolean);
  container.replaceChildren();
  for (const paragraphText of paragraphs.length ? paragraphs : [""]) {
    const paragraph = document.createElement("p");
    appendInlineMarkdown(paragraph, paragraphText.replace(/\n/g, " "));
    container.append(paragraph);
  }
}

function appendInlineMarkdown(parent, text) {
  const tokenPattern = /(\*\*([^*]+)\*\*|\*([^*]+)\*|\[([^\]]+)\]\((https?:\/\/[^)\s]+)\))/g;
  let lastIndex = 0;
  for (const match of text.matchAll(tokenPattern)) {
    if (match.index > lastIndex) parent.append(document.createTextNode(text.slice(lastIndex, match.index)));
    if (match[2]) {
      const strong = document.createElement("strong");
      strong.textContent = match[2];
      parent.append(strong);
    } else if (match[3]) {
      const em = document.createElement("em");
      em.textContent = match[3];
      parent.append(em);
    } else if (match[4] && match[5]) {
      const link = document.createElement("a");
      link.href = match[5];
      link.target = "_blank";
      link.rel = "noopener";
      link.textContent = match[4];
      parent.append(link);
    }
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < text.length) parent.append(document.createTextNode(text.slice(lastIndex)));
}
