// Ride gallery overlay: loads gallery.json (generated by
// scripts/generate_gallery_json.py) and renders route cards into the
// fullscreen gallery dialog. The "Browse gallery" button stays hidden when
// the file is absent. Each card shows the curated title/description plus
// stats computed by the generator from the GPX itself (distance, ascent,
// a mini elevation profile) and the same distance/terrain/difficulty
// classification the app shows for a loaded route.

import { classifyRoute } from "./difficulty.mjs";
import { formatAltitude, formatDistance } from "./units.mjs";

// Dot color for the class badge, keyed by difficulty label (difficulty.mjs).
const DIFFICULTY_COLORS = {
  "Very Easy": "#4ec06f",
  "Easy": "#4ec06f",
  "Moderate": "#e8b74e",
  "Hard": "#e8823c",
  "Very Hard": "#d9542f",
  "Epic": "#d9542f",
};

// Grade buckets for the mini profile strip — same palette as profile.mjs.
function miniBarColor(gradePercent) {
  if (gradePercent <= -0.6) return "#57b877";
  if (gradePercent < 0.8) return "rgba(200, 206, 214, 0.55)";
  if (gradePercent < 3.5) return "#e8b74e";
  if (gradePercent < 7) return "#e8823c";
  return "#d9542f";
}

const cards = [];
let els = null;

export async function initGallery(onLoadRoute, {
  shouldAutoLoadFirst = () => false,
  getCurrentRouteName = () => null,
  getDistanceUnits = () => "metric",
} = {}) {
  let routes;
  try {
    const response = await fetch("./gallery.json");
    if (!response.ok) return;
    routes = (await response.json()).routes;
  } catch {
    return; // gallery.json not present — gallery stays hidden
  }
  if (!routes?.length) return;

  els = {
    dialog: document.getElementById("galleryDialog"),
    grid: document.getElementById("galleryGrid"),
    count: document.getElementById("galleryCount"),
    closeBtn: document.getElementById("galleryCloseBtn"),
    browseBtn: document.getElementById("browseGalleryBtn"),
    browseCount: document.getElementById("browseGalleryCount"),
  };

  const loadRoute = async (route) => {
    await onLoadRoute(route.gpx, route.title);
    refreshCards(getCurrentRouteName, getDistanceUnits);
    els.dialog.close();
  };

  for (const route of routes) {
    els.grid.append(buildCard(route, loadRoute));
  }
  refreshCards(getCurrentRouteName, getDistanceUnits);

  els.count.textContent = `${routes.length} route${routes.length === 1 ? "" : "s"}`;
  els.browseCount.textContent = String(routes.length);
  els.browseBtn.hidden = false;
  els.browseBtn.addEventListener("click", () => {
    refreshCards(getCurrentRouteName, getDistanceUnits);
    els.dialog.showModal();
  });
  els.closeBtn.addEventListener("click", () => els.dialog.close());

  // First visit with nothing loaded yet: start with the first gallery ride
  // instead of an empty map. shouldAutoLoadFirst is re-checked here (after
  // the await) in case a saved ride or a user pick landed in the meantime.
  if (routes[0].gpx && shouldAutoLoadFirst()) {
    await onLoadRoute(routes[0].gpx, routes[0].title);
    refreshCards(getCurrentRouteName, getDistanceUnits);
  }
}

// Re-sync the per-card bits that depend on app state: which route is
// currently loaded, and the unit the stats are displayed in.
function refreshCards(getCurrentRouteName, getDistanceUnits) {
  const currentName = getCurrentRouteName();
  const units = getDistanceUnits();
  for (const card of cards) {
    const loaded = card.route.title === currentName;
    card.root.classList.toggle("loaded", loaded);
    card.loadedBadge.hidden = !loaded;
    card.button.textContent = loaded ? "Loaded" : "Load route";
    if (card.lengthStat) {
      card.lengthStat.textContent = formatDistance(card.route.distanceMeters, units, 1);
      card.ascentStat.textContent = formatAltitude(card.route.ascentMeters, units);
    }
  }
}

function buildCard(route, loadRoute) {
  const card = document.createElement("article");
  card.className = "gallery-card";

  // thumbnail with class badge + LOADED badge
  const thumb = document.createElement("div");
  thumb.className = "gallery-card-thumb";
  if (route.screenshot) {
    const img = document.createElement("img");
    img.src = route.screenshot;
    img.alt = route.title;
    img.loading = "lazy";
    thumb.append(img);
  }

  const classification = Number.isFinite(route.distanceMeters)
    ? classifyRoute(route.distanceMeters, route.ascentMeters ?? 0)
    : null;
  if (classification) {
    const badge = document.createElement("div");
    badge.className = "gallery-card-badge";
    const dot = document.createElement("i");
    dot.style.background = DIFFICULTY_COLORS[classification.difficulty] ?? "#e8b74e";
    const text = document.createElement("span");
    text.textContent =
      `${classification.distanceClass} · ${classification.terrainClass} · ${classification.difficulty}`;
    badge.append(dot, text);
    thumb.append(badge);
  }

  const loadedBadge = document.createElement("div");
  loadedBadge.className = "gallery-card-loaded-badge";
  loadedBadge.textContent = "LOADED";
  loadedBadge.hidden = true;
  thumb.append(loadedBadge);

  const attribution = document.createElement("span");
  attribution.className = "gallery-card-attribution";
  attribution.textContent = "Google";
  thumb.append(attribution);
  card.append(thumb);

  // mini grade-colored elevation strip
  if (route.elevations?.length > 2 && Number.isFinite(route.distanceMeters)) {
    card.append(buildMiniProfile(route.elevations, route.distanceMeters));
  }

  // body: title · description · stats · CTA
  const body = document.createElement("div");
  body.className = "gallery-card-body";

  const title = document.createElement("h3");
  title.className = "gallery-card-title";
  title.textContent = route.title;

  const desc = document.createElement("p");
  desc.className = "gallery-card-desc";
  desc.textContent = descriptionText(route);

  body.append(title, desc);

  let lengthStat = null;
  let ascentStat = null;
  if (classification) {
    const stats = document.createElement("div");
    stats.className = "gallery-card-stats";
    const length = buildStat("Length", "");
    const ascent = buildStat("Total ascent", "accent");
    stats.append(length.wrap, ascent.wrap);
    body.append(stats);
    lengthStat = length.stat;
    ascentStat = ascent.stat;
  }

  const button = document.createElement("button");
  button.type = "button";
  button.className = "gallery-card-btn";
  button.textContent = "Load route";
  button.addEventListener("click", () => loadRoute(route));
  body.append(button);
  card.append(body);

  cards.push({ route, root: card, loadedBadge, button, lengthStat, ascentStat });
  return card;
}

function buildStat(label, valueClass) {
  const wrap = document.createElement("div");
  wrap.className = "gallery-card-stat";
  const name = document.createElement("span");
  name.textContent = label;
  const stat = document.createElement("strong");
  if (valueClass) stat.className = valueClass;
  stat.textContent = "--";
  wrap.append(name, stat);
  return { wrap, stat };
}

function buildMiniProfile(elevations, distanceMeters) {
  const strip = document.createElement("div");
  strip.className = "gallery-card-profile";
  const min = Math.min(...elevations);
  const max = Math.max(...elevations);
  const span = Math.max(1, max - min);
  const sampleMeters = distanceMeters / (elevations.length - 1);
  elevations.forEach((ele, index) => {
    const bar = document.createElement("i");
    const grade = index > 0 ? ((ele - elevations[index - 1]) / sampleMeters) * 100 : 0;
    bar.style.height = `${(8 + ((ele - min) / span) * 92).toFixed(1)}%`;
    bar.style.background = miniBarColor(grade);
    strip.append(bar);
  });
  return strip;
}

// Card description: the curated text minus the trailing "**10 km** · …"
// stats line, which the structured stat tiles below the text now cover.
function descriptionText(route) {
  const lines = route.description.split("\n").map((line) => line.trim());
  while (lines.length && (lines.at(-1) === "" || /^\*\*[\d.,]/.test(lines.at(-1)))) {
    lines.pop();
  }
  return lines.join(" ").replace(/\*\*/g, "");
}
